## Deliverable 2. Create a Customer Travel Destinations Map.

In [2]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import gmaps.datasets

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [3]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Khorramshahr,IR,30.4397,48.1664,51.75,27,0,7.63,clear sky
1,1,Ushuaia,AR,-54.8000,-68.3000,53.26,66,75,10.36,broken clouds
2,2,Cayenne,GF,4.9333,-52.3333,80.10,1,75,10.36,broken clouds
3,3,Garmsar,IR,35.2182,52.3409,48.83,33,0,15.70,clear sky
4,4,Kuybysheve,UA,47.3580,36.6491,34.27,61,0,6.29,clear sky

In [4]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [5]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
prefered_city_df=city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & (city_data_df["Max Temp"]>= min_temp)]
prefered_city_df.head(50)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
2,2,Cayenne,GF,4.9333,-52.3333,80.10,1,75,10.36,broken clouds
10,10,Touros,BR,-5.1989,-35.4608,79.48,84,100,11.41,light rain
15,15,Gao,ML,16.6362,1.6370,81.79,13,92,10.47,overcast clouds
18,18,San Carlos Del Zulia,VE,9.0000,-71.9135,78.30,81,12,5.97,few clouds
23,23,Mahebourg,MU,-20.4081,57.7000,78.26,80,10,7.76,clear sky
25,25,Quatre Cocos,MU,-20.2078,57.7625,78.10,81,17,7.56,few clouds
38,38,Vila Velha,BR,-20.3297,-40.2925,78.75,88,20,6.91,few clouds
41,41,Georgetown,MY,5.4112,100.3354,87.73,70,20,5.75,few clouds
43,43,Souillac,MU,-20.5167,57.5167,77.38,94,75,0.00,broken clouds
48,48,Muzaffarnagar,IN,29.4667,77.6833,78.80,17,0,10.85,clear sky
56,56,Grand Gaube,MU,-20.0064,57.6608,79.38,86,7,3.00,clear sky
60,60,Miranpur,IN,29.3000,77.9333,79.02,17,0,11.34,clear sky
61,61,Banikoara,BJ,11.2985,2.4386,81.81,16,48,5.17,scattered clouds
65,65,Sanghar,PK,26.0466,68.9481,85.35,15,1,2.06,clear sky
66,66,Antalaha,MG,-14.9003,50.2788,75.36,90,36,4.63,scattered clouds
72,72,Sambava,MG,-14.2667,50.1667,76.91,89,98,5.14,overcast clouds
74,74,Murliganj,IN,25.9000,86.9833,85.98,13,0,8.14,clear sky
79,79,Sabya,SA,17.1495,42.6254,80.22,68,6,2.10,clear sky
86,86,Porto Novo,BJ,6.4965,2.6036,80.73,84,18,4.59,few clouds
89,89,Camocim,BR,-2.9022,-40.8411,76.15,91,100,7.31,overcast clouds
96,96,Kavaratti,IN,10.5669,72.6420,81.73,66,6,4.32,clear sky
97,97,Arlit,NE,18.7369,7.3853,75.85,13,63,6.22,broken clouds
98,98,Sokoni,TZ,-6.4333,39.5500,82.47,75,64,6.35,broken clouds
104,104,Lambarene,GA,-0.7001,10.2406,76.06,95,100,1.68,overcast clouds
109,109,Ratangarh,IN,28.0833,74.6000,83.55,10,0,6.87,clear sky
120,120,Arraial Do Cabo,BR,-22.9661,-42.0278,76.80,91,79,23.09,broken clouds
128,128,Hithadhoo,MV,-0.6000,73.0833,83.53,68,69,12.88,broken clouds
129,129,Padang,ID,-0.9492,100.3543,87.85,58,32,3.56,scattered clouds
135,135,Bodden Town,KY,19.2833,-81.2500,80.60,75,40,2.30,scattered clouds
143,143,Luanda,AO,-8.8368,13.2343,79.18,85,100,4.99,overcast clouds
149,149,Salinopolis,BR,-0.6136,-47.3561,77.36,90,100,7.67,overcast clouds
151,151,Sao Joao Da Barra,BR,-21.6403,-41.0511,78.15,89,91,18.77,overcast clouds
152,152,Saint George,US,37.1041,-113.5841,76.95,15,0,3.44,clear sky
161,161,Manaure,CO,11.7751,-72.4445,78.98,76,71,14.97,broken clouds
162,162,Carnarvon,AU,-24.8667,113.6333,84.27,65,40,14.97,scattered clouds
164,164,Humberto De Campos,BR,-2.5983,-43.4611,75.58,94,100,4.05,moderate rain
170,170,Bengkulu,ID,-3.8004,102.2655,84.69,62,18,5.79,few clouds
171,171,Bambous Virieux,MU,-20.3428,57.7575,78.22,80,14,7.61,few clouds
176,176,Sao Jose Da Coroa Grande,BR,-8.8978,-35.1478,77.31,86,45,3.04,scattered clouds
179,179,Mormugao,IN,15.4000,73.8000,81.32,79,56,2.57,broken clouds
183,183,Natal,BR,-5.7950,-35.2094,75.85,100,75,6.91,broken clouds
185,185,Qandala,SO,11.4720,49.8728,75.22,47,35,0.81,scattered clouds
186,186,Meulaboh,ID,4.1363,96.1285,83.48,72,30,0.96,scattered clouds
191,191,Keffi,NG,8.8486,7.8736,77.54,20,21,3.83,few clouds
196,196,Bathsheba,BB,13.2167,-59.5167,77.61,83,40,20.71,scattered clouds
197,197,Port-Gentil,GA,-0.7193,8.7815,81.63,80,100,8.97,overcast clouds
200,200,Ormara,PK,25.2088,64.6357,80.10,52,0,1.83,clear sky
205,205,Nizwa,OM,22.9333,57.5333,76.15,19,15,1.19,few clouds
207,207,Hobyo,SO,5.3505,48.5268,79.84,79,100,15.23,moderate rain
214,214,Sokolo,ML,14.7328,-6.1219,85.82,34,6,6.58,clear sky

In [6]:
# 4a. Determine if there are any empty rows.
prefered_city_df.isnull().count()
prefered_city_df.isnull().sum()

City_ID                0
City                   0
Country                0
Lat                    0
Lng                    0
Max Temp               0
Humidity               0
Cloudiness             0
Wind Speed             0
Current Description    0
dtype: int64

In [7]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
#- There is no Empty row

In [8]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = prefered_city_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
2,Cayenne,GF,80.10,broken clouds,4.9333,-52.3333,
10,Touros,BR,79.48,light rain,-5.1989,-35.4608,
15,Gao,ML,81.79,overcast clouds,16.6362,1.6370,
18,San Carlos Del Zulia,VE,78.30,few clouds,9.0000,-71.9135,
23,Mahebourg,MU,78.26,clear sky,-20.4081,57.7000,
25,Quatre Cocos,MU,78.10,few clouds,-20.2078,57.7625,
38,Vila Velha,BR,78.75,few clouds,-20.3297,-40.2925,
41,Georgetown,MY,87.73,few clouds,5.4112,100.3354,
43,Souillac,MU,77.38,broken clouds,-20.5167,57.5167,
48,Muzaffarnagar,IN,78.80,clear sky,29.4667,77.6833,

In [9]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
 
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # 6c. Get latitude and longitude from DataFrame
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [10]:
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
2,Cayenne,GF,80.10,broken clouds,4.9333,-52.3333,Hôtel Le Dronmi
10,Touros,BR,79.48,light rain,-5.1989,-35.4608,INN NEW HORIZON
15,Gao,ML,81.79,overcast clouds,16.6362,1.6370,
18,San Carlos Del Zulia,VE,78.30,few clouds,9.0000,-71.9135,Hotel El Manantial
23,Mahebourg,MU,78.26,clear sky,-20.4081,57.7000,Shandrani Beachcomber Resort & Spa
25,Quatre Cocos,MU,78.10,few clouds,-20.2078,57.7625,Sunrise Attitude Hotel
38,Vila Velha,BR,78.75,few clouds,-20.3297,-40.2925,Hotel Vitória Palace
41,Georgetown,MY,87.73,few clouds,5.4112,100.3354,Cititel Penang
43,Souillac,MU,77.38,broken clouds,-20.5167,57.5167,Shanti Maurice Resort & Spa
48,Muzaffarnagar,IN,78.80,clear sky,29.4667,77.6833,Hotel Green Apple

In [11]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df = hotel_df[hotel_df["Hotel Name"]!= '']
clean_hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
2,Cayenne,GF,80.10,broken clouds,4.9333,-52.3333,Hôtel Le Dronmi
10,Touros,BR,79.48,light rain,-5.1989,-35.4608,INN NEW HORIZON
18,San Carlos Del Zulia,VE,78.30,few clouds,9.0000,-71.9135,Hotel El Manantial
23,Mahebourg,MU,78.26,clear sky,-20.4081,57.7000,Shandrani Beachcomber Resort & Spa
25,Quatre Cocos,MU,78.10,few clouds,-20.2078,57.7625,Sunrise Attitude Hotel
38,Vila Velha,BR,78.75,few clouds,-20.3297,-40.2925,Hotel Vitória Palace
41,Georgetown,MY,87.73,few clouds,5.4112,100.3354,Cititel Penang
43,Souillac,MU,77.38,broken clouds,-20.5167,57.5167,Shanti Maurice Resort & Spa
48,Muzaffarnagar,IN,78.80,clear sky,29.4667,77.6833,Hotel Green Apple
56,Grand Gaube,MU,79.38,clear sky,-20.0064,57.6608,Veranda Paul et Virginie Hotel & Spa

In [14]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [16]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [19]:
# 11a. Add a marker layer for each city to the map. 
locations = clean_hotel_df[["Lat", "Lng"]]
max_temp = clean_hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))